In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import f1_score,classification_report

In [2]:
data=pd.read_csv(r"C:\Users\asdf\Documents\D.S\INEURON-PROJECTS\Tour_Package_Project\data\tour_package.csv")

In [3]:
data.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

### Now see the Null values and Handle them

In [4]:
data.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [5]:
data=data.drop("CustomerID",axis=1)

In [6]:
data.head()

,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

as we know from eda part we need to handle some feature engineering on the columns which have different values

In [7]:
data["Gender"]=np.where(data["Gender"]=="Fe Male","Female",data["Gender"])
data["MaritalStatus"]=np.where(data["MaritalStatus"]=="Single","Unmarried",data["MaritalStatus"])

In [8]:
y=data["ProdTaken"]
y

0       1
1       0
2       1
3       0
4       0
       ..
4883    1
4884    1
4885    1
4886    1
4887    1
Name: ProdTaken, Length: 4888, dtype: int64

In [9]:
y.shape

(4888,)

In [10]:
x=data.drop("ProdTaken",axis=1)

In [11]:
x.shape

(4888, 18)

In [12]:
column_names=x.columns
column_names

Index(['Age', 'TypeofContact', 'CityTier', 'DurationOfPitch', 'Occupation',
       'Gender', 'NumberOfPersonVisiting', 'NumberOfFollowups',
       'ProductPitched', 'PreferredPropertyStar', 'MaritalStatus',
       'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [14]:
x_train

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
2962,39.0,Self Enquiry,3,14.0,Small Business,Female,3,5.0,Deluxe,3.0,Unmarried,2.0,0,2,1,2.0,Manager,22706.0
1788,27.0,Self Enquiry,1,11.0,Salaried,Female,2,3.0,Basic,4.0,Unmarried,2.0,1,3,0,1.0,Executive,17478.0
3499,35.0,Company Invited,1,22.0,Small Business,Male,4,4.0,Super Deluxe,5.0,Married,NaN,0,4,1,3.0,AVP,35685.0
3173,36.0,Self Enquiry,1,32.0,Small Business,Female,3,4.0,Standard,3.0,Married,3.0,1,3,1,2.0,Senior Manager,29066.0
3126,33.0,Company Invited,1,7.0,Salaried,Female,4,5.0,Basic,4.0,Divorced,8.0,0,3,1,1.0,Executive,21010.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4426,28.0,Self Enquiry,1,10.0,Small Business,Male,3,5.0,Basic,3.0,Unmarried,2.0,0,1,1,2.0,Executive,20723.0
466,41.0,Self Enquiry,3,8.0,Salaried,Female,3,3.0,Super Deluxe,5.0,Divorced,1.0,0,5,1,1.0,AVP,31595.0
3092,38.0,Company Invited,3,28.0,Small Business,Female,3,4.0,Basic,3.0,Divorced,7.0,0,2,1,2.0,Executive,21651.0
3772,28.0,Self Enquiry,3,30.0,Small Business,Female,3,5.0,Deluxe,3.0,Married,3.0,0,1,1,2.0,Manager,22218.0
860,22.0,Company Invited,1,9.0,Salaried,Male,2,4.0,Basic,3.0,Divorced,1.0,1,3,0,0.0,Executive,17853.0

In [15]:
num_features=x_train.select_dtypes([float,int]).columns
cat_features=x_train.select_dtypes(object).columns

In [16]:
num_features

Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips',
       'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'NumberOfChildrenVisiting', 'MonthlyIncome'],
      dtype='object')

In [17]:
cat_features

Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')

In [18]:
num_pipeline=Pipeline(steps=[
    ("Imputer",SimpleImputer(strategy="mean")),
    ("Scaling",StandardScaler())
])

In [19]:
num_pipeline

Pipeline(steps=[('Imputer', SimpleImputer()), ('Scaling', StandardScaler())])

In [20]:
cat_pipeline=Pipeline(steps=[
    ("imputing",SimpleImputer(strategy="most_frequent")),
    ("Encoding",OneHotEncoder())
])

In [21]:
cat_pipeline

Pipeline(steps=[('imputing', SimpleImputer(strategy='most_frequent')),
                ('Encoding', OneHotEncoder())])

In [22]:
preprocessor=ColumnTransformer([
    ("num_pipeline",num_pipeline,num_features),
    ("cat_pipeline",cat_pipeline,cat_features)
])

In [23]:
preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('Imputer', SimpleImputer()),
                                                 ('Scaling',
                                                  StandardScaler())]),
                                 Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips',
       'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'NumberOfChildrenVisiting', 'MonthlyIncome'],
      dtype='object')),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputing',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('Encoding',
                                                  OneHotEncoder())]),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object'))])

In [24]:
preprocessor=preprocessor.fit(x_train)

In [25]:
x_train

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
2962,39.0,Self Enquiry,3,14.0,Small Business,Female,3,5.0,Deluxe,3.0,Unmarried,2.0,0,2,1,2.0,Manager,22706.0
1788,27.0,Self Enquiry,1,11.0,Salaried,Female,2,3.0,Basic,4.0,Unmarried,2.0,1,3,0,1.0,Executive,17478.0
3499,35.0,Company Invited,1,22.0,Small Business,Male,4,4.0,Super Deluxe,5.0,Married,NaN,0,4,1,3.0,AVP,35685.0
3173,36.0,Self Enquiry,1,32.0,Small Business,Female,3,4.0,Standard,3.0,Married,3.0,1,3,1,2.0,Senior Manager,29066.0
3126,33.0,Company Invited,1,7.0,Salaried,Female,4,5.0,Basic,4.0,Divorced,8.0,0,3,1,1.0,Executive,21010.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4426,28.0,Self Enquiry,1,10.0,Small Business,Male,3,5.0,Basic,3.0,Unmarried,2.0,0,1,1,2.0,Executive,20723.0
466,41.0,Self Enquiry,3,8.0,Salaried,Female,3,3.0,Super Deluxe,5.0,Divorced,1.0,0,5,1,1.0,AVP,31595.0
3092,38.0,Company Invited,3,28.0,Small Business,Female,3,4.0,Basic,3.0,Divorced,7.0,0,2,1,2.0,Executive,21651.0
3772,28.0,Self Enquiry,3,30.0,Small Business,Female,3,5.0,Deluxe,3.0,Married,3.0,0,1,1,2.0,Manager,22218.0
860,22.0,Company Invited,1,9.0,Salaried,Male,2,4.0,Basic,3.0,Divorced,1.0,1,3,0,0.0,Executive,17853.0

In [26]:
x_train=preprocessor.transform(x_train)
x_train

array([[ 0.16752713,  1.4834196 , -0.17769967, ...,  1.        ,
         0.        ,  0.        ],
       [-1.15621181, -0.70823914, -0.54478249, ...,  0.        ,
         0.        ,  0.        ],
       [-0.27371919, -0.70823914,  0.80118788, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.05721555,  1.4834196 ,  1.53535353, ...,  0.        ,
         0.        ,  0.        ],
       [-1.04590023,  1.4834196 ,  1.78007542, ...,  1.        ,
         0.        ,  0.        ],
       [-1.7077697 , -0.70823914, -0.78950438, ...,  0.        ,
         0.        ,  0.        ]])

In [27]:
x_test=preprocessor.transform(x_test)

In [28]:
x_train.shape,x_test.shape

((3274, 33), (1614, 33))

In [29]:
column_names

Index(['Age', 'TypeofContact', 'CityTier', 'DurationOfPitch', 'Occupation',
       'Gender', 'NumberOfPersonVisiting', 'NumberOfFollowups',
       'ProductPitched', 'PreferredPropertyStar', 'MaritalStatus',
       'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

In [30]:
new_columns=pd.get_dummies(x,columns=cat_features).columns

In [31]:
new_columns

Index(['Age', 'CityTier', 'DurationOfPitch', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'PreferredPropertyStar', 'NumberOfTrips',
       'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'NumberOfChildrenVisiting', 'MonthlyIncome',
       'TypeofContact_Company Invited', 'TypeofContact_Self Enquiry',
       'Occupation_Free Lancer', 'Occupation_Large Business',
       'Occupation_Salaried', 'Occupation_Small Business', 'Gender_Female',
       'Gender_Male', 'ProductPitched_Basic', 'ProductPitched_Deluxe',
       'ProductPitched_King', 'ProductPitched_Standard',
       'ProductPitched_Super Deluxe', 'MaritalStatus_Divorced',
       'MaritalStatus_Married', 'MaritalStatus_Unmarried', 'Designation_AVP',
       'Designation_Executive', 'Designation_Manager',
       'Designation_Senior Manager', 'Designation_VP'],
      dtype='object')

In [32]:
pd.DataFrame(x_train,columns=new_columns)

,Age,CityTier,DurationOfPitch,NumberOfPersonVisiting,NumberOfFollowups,PreferredPropertyStar,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,...,ProductPitched_Standard,ProductPitched_Super Deluxe,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Unmarried,Designation_AVP,Designation_Executive,Designation_Manager,Designation_Senior Manager,Designation_VP
0,0.167527,1.483420,-0.177700,0.125643,1.282986,-0.731366,-0.678533,-0.637936,-0.776562,0.783328,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,-1.156212,-0.708239,-0.544782,-1.264066,-0.719965,0.523065,-0.678533,1.567556,-0.047645,-1.276604,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2,-0.273719,-0.708239,0.801188,1.515352,0.281511,1.777496,0.000000,-0.637936,0.681272,0.783328,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,-0.163408,-0.708239,2.024797,0.125643,0.281511,-0.731366,-0.134543,1.567556,-0.047645,0.783328,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.494342,-0.708239,-1.034226,1.515352,1.282986,0.523065,2.585408,-0.637936,-0.047645,0.783328,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,-1.045900,-0.708239,-0.667143,0.125643,1.282986,-0.731366,-0.678533,-0.637936,-1.505478,0.783328,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3270,0.388150,1.483420,-0.911865,0.125643,-0.719965,1.777496,-1.222523,-0.637936,1.410189,0.783328,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3271,0.057216,1.483420,1.535354,0.125643,0.281511,-0.731366,2.041418,-0.637936,-0.776562,0.783328,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3272,-1.045900,1.483420,1.780075,0.125643,1.282986,-0.731366,-0.134543,-0.637936,-1.505478,0.783328,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3273,-1.707770,-0.708239,-0.789504,-1.264066,0.281511,-0.731366,-1.222523,1.567556,-0.047645,-1.276604,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

### Define the Models

In [34]:
models={
    "Logistic Regression":LogisticRegression(),
    "Random Forest Classifier":RandomForestClassifier(),
    "Naive Bayes Classifier":GaussianNB(),
    "Decision Tree Classifier":DecisionTreeClassifier(),
    "Support Vector Machine":SVC(),
    "KNeighborsClassifier":KNeighborsClassifier()
}

In [39]:
list(models)

['Logistic Regression',
 'Random Forest Classifier',
 'Naive Bayes Classifier',
 'Decision Tree Classifier',
 'Support Vector Machine',
 'KNeighborsClassifier']

In [45]:
list(models.values())[0]

LogisticRegression()

In [57]:
def Model_Training(model_dict,x_train_data,y_train_data):
    for i in range(len(list(model_dict))):
        model=list(model_dict.values())[i]
        model.fit(x_train_data,y_train_data)
        y_pred_train=model.predict(x_train_data)
        report=classification_report(y_pred_train,y_train_data)
        print(model)
        print(report)

In [58]:
Model_Training(models,x_train,y_train)

LogisticRegression()
              precision    recall  f1-score   support

           0       0.97      0.86      0.91      2992
           1       0.32      0.72      0.45       282

    accuracy                           0.85      3274
   macro avg       0.65      0.79      0.68      3274
weighted avg       0.91      0.85      0.87      3274

RandomForestClassifier()
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2647
           1       1.00      1.00      1.00       627

    accuracy                           1.00      3274
   macro avg       1.00      1.00      1.00      3274
weighted avg       1.00      1.00      1.00      3274

GaussianNB()
              precision    recall  f1-score   support

           0       1.00      0.81      0.90      3242
           1       0.04      0.84      0.08        32

    accuracy                           0.82      3274
   macro avg       0.52      0.83      0.49      3274
weighted avg       0.99      0.82      0.89      3274

DecisionTreeClassifier()
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2647
           1       1.00      1.00      1.00       627

    accuracy                           1.00      3274
   macro avg       1.00      1.00      1.00      3274
weighted avg       1.00      1.00      1.00      3274

SVC()
              precision    recall  f1-score   support

           0       0.99      0.89      0.94      2928
           1       0.50      0.91      0.65       346

    accuracy                           0.90      3274
   macro avg       0.75      0.90      0.79      3274
weighted avg       0.94      0.90      0.91      3274

KNeighborsClassifier()
              precision    recall  f1-score   support

           0       0.98      0.94      0.96      2782
           1       0.72      0.91      0.80       492

    accuracy                           0.93      3274
   macro avg       0.85      0.93      0.88      3274
weighted avg       0.94      0.93      0.94      3274

In [60]:
data["ProdTaken"].value_counts()  #it is not the Imbalanced Dataset

0    3968
1     920
Name: ProdTaken, dtype: int64